name: shift_sl
description: "A Flutter app for managing hospital shift schedules."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utility
  table_calendar: ^3.2.0
  http: ^1.3.0
  provider: ^6.1.2
  intl: ^0.20.2
  logger: ^2.5.0
  flutter_native_splash: 2.4.4
  smooth_page_indicator: ^1.2.1

  get: ^4.7.2
  get_storage: ^2.1.1

  shared_preferences: ^2.2.2  

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.4.4



  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/my_app_icon.png"
  adaptive_icon_background: "assets/icons/adaptive_bg.png"

flutter_icons:
  image_path: "assets/logos/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/on_boarding/
    - assets/images/on_boarding/Group.svg
    - assets/images/on_boarding/employee-works-on-deadlines.svg
    - assets/images/on_boarding/onboarding1.png
    - assets/images/on_boarding/onboarding2.png
    - assets/images/on_boarding/onboarding3.png
    - assets/logos/
    - assets/logos/adaptive_icon.png
    - assets/logos/iconV2.png
