name: shift_sl
description: "A Flutter app for managing hospital shift schedules."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #utility
  table_calendar: 3.1.3
  http: ^1.3.0
  provider: ^6.1.2
  intl: ^0.19.0
  logger: ^2.5.0
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.17
  awesome_snackbar_content: ^0.1.5

  get: ^4.7.2
  get_storage: ^2.1.1

  #icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  google_fonts: ^6.2.1

  firebase_core: ^2.25.4
  firebase_auth: ^4.16.0  # ✅ <-- Update this!
  cloud_firestore: ^4.13.5
  firebase_messaging: ^14.7.8
  firebase_storage: ^11.6.6


  shared_preferences: ^2.2.2  # Latest stable version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/icon.png"
  adaptive_icon_background: "#2B3C56"
  adaptive_icon_foreground: "assets/logos/iconV2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/on_boarding/
    - assets/images/
    - assets/logos/
